In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
DATASET_PATH = "/Users/zhejianpeng/project/environment_sensing_crs/dataset/ml-25m/"
genome_scores = DATASET_PATH + "genome-scores.csv"
link = DATASET_PATH + "links.csv"
rating = DATASET_PATH + "ratings.csv"
genome_tags = DATASET_PATH + "genome-tags.csv"
movie = DATASET_PATH + "movies.csv"
tag = DATASET_PATH + "tags.csv"

In [3]:
genome_scores = pd.read_csv(genome_scores)
link = pd.read_csv(link)
rating = pd.read_csv(rating)
genome_tags = pd.read_csv(genome_tags)
movie = pd.read_csv(movie)
tag = pd.read_csv(tag)

In [4]:
len(genome_scores.movieId.unique())

13816

In [5]:
genome_scores

          movieId  tagId  relevance
0               1      1    0.02875
1               1      2    0.02375
2               1      3    0.06250
3               1      4    0.07575
4               1      5    0.14075
...           ...    ...        ...
15584443   206499   1124    0.11000
15584444   206499   1125    0.04850
15584445   206499   1126    0.01325
15584446   206499   1127    0.14025
15584447   206499   1128    0.03350

[15584448 rows x 3 columns]

In [6]:
link

       movieId   imdbId    tmdbId
0            1   114709     862.0
1            2   113497    8844.0
2            3   113228   15602.0
3            4   114885   31357.0
4            5   113041   11862.0
...        ...      ...       ...
62418   209157  6671244  499546.0
62419   209159   297986   63407.0
62420   209163  6755366  553036.0
62421   209169   249603  162892.0
62422   209171    55323   79513.0

[62423 rows x 3 columns]

In [7]:
len(rating.movieId.unique())

59047

In [8]:
genome_tags

      tagId           tag
0         1           007
1         2  007 (series)
2         3  18th century
3         4         1920s
4         5         1930s
...     ...           ...
1123   1124       writing
1124   1125         wuxia
1125   1126          wwii
1126   1127        zombie
1127   1128       zombies

[1128 rows x 2 columns]

In [9]:
len(movie.movieId.unique())

62423

In [10]:
tag

         userId  movieId                  tag   timestamp
0             3      260              classic  1439472355
1             3      260               sci-fi  1439472256
2             4     1732          dark comedy  1573943598
3             4     1732       great dialogue  1573943604
4             4     7569     so bad it's good  1573943455
...         ...      ...                  ...         ...
1093355  162521    66934  Neil Patrick Harris  1427311611
1093356  162521   103341     cornetto trilogy  1427311259
1093357  162534   189169               comedy  1527518175
1093358  162534   189169             disabled  1527518181
1093359  162534   189169              robbery  1527518193

[1093360 rows x 4 columns]

In [11]:
len(tag.movieId.unique())

45251

In [14]:
movie

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
62418,209157,We (2018),Drama
62419,209159,Window of the Soul (2001),Documentary
62420,209163,Bad Poems (2018),Comedy|Drama
62421,209169,A Girl Thing (2001),(no genres listed)
62422,209171,Women of Devil's Island (1962),Action|Adventure|Drama